fs.delete("startup.lua")
fs.delete("json.lua")
fs.delete("create.lua")
fs.copy("disk/code.lua", "startup.lua")
fs.copy("disk/startup.lua", "create.lua")
fs.copy("disk/json.lua", "json.lua")
fs.delete("disk/startup.lua")
fs.delete("disk/code.lua")
fs.delete("disk/json.lua")
os.reboot()
